site_name: "demo_breeding"
site_description: "new trial doc "
repo_url: https://github.com/Bayer/breeding-dataform-velocity-docs
edit_uri: edit/main/docs

nav:
  - Introduction: index.md

plugins:
  - techdocs-core